version: "3.7"
services:
    pecax:
        image: pecax/pecax
        container_name: pecax
        restart: unless-stopped
        ports:
            - "3030:3030"
        depends_on:
            - biographvisart
            - nextflow
            - sbml4j
            - arangodb
    arangodb:
        image: arangodb/arangodb
        container_name: arangodb
        restart: unless-stopped
        environment:
            ARANGO_NO_AUTH: 0
        expose:
            - "8529"
        volumes:
            - arangodb_data_container:/var/lib/arangodb3
            - arangodb_apps_data_container:/var/lib/arangodb3-apps
    biographvisart:
        image: pecax/biographvisart
        container_name: biographvisart
        restart: unless-stopped
        ports:
            - "3000:3000"
    
    vep_files_GRCh37:
        image: pecax/clinvap_file_deploy:vP_GRCh37
        container_name: vep_files_GRCh37
        volumes: 
          - clinvap_downloads:/mnt
    
    vep_files_GRCh38:
        image: pecax/clinvap_file_deploy:vP_GRCh38
        container_name: vep_files_GRCh38
        volumes: 
          - clinvap_downloads:/mnt

    flask:
        image: pecax/clinvap_api_flask
        # build: ./flask
        container_name: flask
        restart: always
        environment:
            - APP_NAME=MyFlaskApp
            - FLASK_ENV=development
        expose:
            - 8080
        volumes:
            - clinvap_uploads:/app/app/static/input/uploads
            - clinvap_conf:/app/app/static/input/nf_conf
            - clinvap_downloads:/app/app/static/output/downloads

    nginx:
        image: pecax/clinvap_api_nginx
        # build: ./nginx
        container_name: nginx
        restart: always
        expose:
            - "80"

    nextflow:
        image: pecax/clinvap_api_nextflow
        # build: ./nextflow
        container_name: nextflow
        # command: GRCh37
        volumes:
            - clinvap_uploads:/nextflow_pipeline/uploads
            - clinvap_downloads:/nextflow_pipeline/downloads
            - clinvap_conf:/nextflow_pipeline/clinvap_conf
        depends_on:
            - flask
            - nginx

    sbml4jdatabase:
        image: neo4j:4.1
        container_name: sbml4jdb
        volumes:
            - sbml4j_neo4j_vol:/vol
        expose:
            - "7474"
            - "7687"
        environment:
            - NEO4J_CONF=/vol/conf
            - NEO4J_dbms_security_auth__enabled=false
            - NEO4J_dbms_memory_pagecache_size=1G
            - NEO4J_dbms_memory_heap_initial__size=2G
            - NEO4J_dbms_memory_heap_max__size=2G
            - NEO4J_dbms_security_procedures_unrestricted=apoc.algo.dijkstraWithDefaultWeight, apoc.path.expand
            - NEO4J_dbms_security_procedures_whitelist=apoc.algo.dijkstraWithDefaultWeight, apoc.path.expand
        restart: unless-stopped
        command: ["neo4j"]
 
    sbml4j:
        image: pecax/sbml4j:1.0
        container_name: sbml4j
        volumes:
            - sbml4j_service_vol:/logs
        environment:
            - SPRING_PROFILES_ACTIVE=test
            - SPRING_DATA_NEO4j_URI=bolt://sbml4jdb:7687
            - SERVER_SERVLET_CONTEXTPATH=/sbml4j
            - SERVER_PORT=8080
            - OVERVIEWNETWORK_DEFAULT_BASE-NETWORK-NAME=PeCaX-Base
            - OVERVIEWNETWORK_DEFAULT_MINSIZE=0
            - OVERVIEWNETWORK_DEFAULT_MAXSIZE=2
            - OVERVIEWNETWORK_DEFAULT_TERMINATEAT=Drugtarget
            - OVERVIEWNETWORK_DEFAULT_DIRECTION=upstream
            - sbml4j.context.minSize=1
            - sbml4j.context.maxSize=3
            - sbml4j.context.terminateAt=Drug
            - sbml4j.context.direction=both
            - SBML4J_OUTPUT_HIDE_MODEL_U-U-I-DS=False
            - SBML4J_NETWORK_HARD-DELETE=True
            - SBML4J_NETWORK_FORCE-DELETE-OF-PUBLIC-NETWORK=False
            - SBML4J_NETWORK_DELETE-EXISTING=True
            - SBML4J_NETWORK_DELETE-DERIVED=True
            - SBML4J_NETWORK_USE-SHARED-PATHWAY-SEARCH=False
            - SBML4J_NETWORK_PUBLIC-USER=sbml4j
            - SBML4J_NETWORK_SHOW-INACTIVE-NETWORKS=False
            - SBML4J_NETWORK_ALLOW-INACTIVE-DUPLICATES=True
            - SBML4J_ANNOTATION_APPEND=True
            - SBML4J_ANNOTATION_KEGGGENESSEPARATOR=+
            - SBML4J_ANNOTATION_ANNOTATE-WITH-LINKS=True
            - sbml4j.csv.matching-column-name[0]=gene name
            - sbml4j.csv.matching-column-name[1]=genename
            - sbml4j.csv.matching-column-name[2]=gene.name
            - sbml4j.csv.matching-column-name[3]=gene_name
            - sbml4j.csv.matching-column-name[4]=gene symbol
            - sbml4j.csv.matching-column-name[5]=genesymbol
            - sbml4j.csv.matching-column-name[6]=gene.symbol
            - sbml4j.csv.matching-column-name[7]=gene_symbol
            - sbml4j.csv.matching-column-name[8]=gene
            - sbml4j.csv.matching-column-name[9]=symbol 
            - SBML4J_externalresources_mdanderson_add-md-anderson-annotation=True
            - SBML4J_externalresources_mdanderson_genelist=ABL1, AKT1, ALK, BRAF, CDK4, CDK6, CDKN2A, EGFR, ERBB2, FGFR1, FGFR2, FLT3, IDH1, KDR, KIT, KRAS, MDM2, MET, NRAS, NTRK1, NTRK2, PDGFRA, PIK3CA, PIK3R1, PTCH1, PTEN, PTPN11, PET, ROS1, SMO
            - SBML4J_externalresources_mdanderson_baseurl=https://pct.mdanderson.org/home/
            - SBML4J_externalresources_mdanderson_section=Overview
            - SBML4J_externalresources_biologicalqualifer_default-database=KEGG
            - SBML4J_externalresources_keggdatabase_pathway-link-prefix=https://www.genome.jp/kegg-bin/show_pathway?
            - SBML4J_externalresources_keggdatabase_pathway-search-prefix=https://www.genome.jp/dbget-bin/www_bfind_sub?dbkey=pathway&keywords=
        depends_on:
            - "sbml4jdatabase"
        ports:
            - "8080:8080"
        restart: on-failure
volumes:
    clinvap_uploads:
    clinvap_downloads:
    clinvap_conf:
    sbml4j_service_vol:
    sbml4j_neo4j_vol:
    arangodb_data_container:
    arangodb_apps_data_container:
