version: "3.7"
services:
    pecax:
        image: mirjamfi/pecax
        container_name: pecax
        restart: unless-stopped
        ports:
            - "3030:3030"
        depends_on:
            - biographvisart
            - nextflow
            - sbml4j
            - arangodb
    arangodb:
        image: arangodb/arangodb
        container_name: arangodb
        restart: unless-stopped
        environment:
            ARANGO_NO_AUTH: 0
        ports:
            - "8529:8529"
        volumes:
            - arangodb_data_container:/var/lib/arangodb3
            - arangodb_apps_data_container:/var/lib/arangodb3-apps
    biographvisart:
        image: mirjamfi/biographvisart
        container_name: biographvisart
        restart: unless-stopped
        ports:
            - "3000:3000"
    
    vep_files_GRCh37:
        image: bilges/clinvap_file_deploy:vP_GRCh37
        container_name: vep_files_GRCh37
        volumes: 
          - clinvap_downloads:/mnt
    
    vep_files_GRCh38:
        image: bilges/clinvap_file_deploy:vP_GRCh38
        container_name: vep_files_GRCh38
        volumes: 
          - clinvap_downloads:/mnt

    flask:
        image: bilges/clinvap_api_flask
        # build: ./flask
        container_name: flask
        restart: always
        environment:
            - APP_NAME=MyFlaskApp
            - FLASK_ENV=development
        expose:
            - 8080
        volumes:
            - clinvap_uploads:/app/app/static/input/uploads
            - clinvap_conf:/app/app/static/input/nf_conf
            - clinvap_downloads:/app/app/static/output/downloads

    nginx:
        image: bilges/clinvap_api_nginx
        # build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"

    nextflow:
        image: bilges/clinvap_api_nextflow
        # build: ./nextflow
        container_name: nextflow
        # command: GRCh37
        volumes:
            - clinvap_uploads:/nextflow_pipeline/uploads
            - clinvap_downloads:/nextflow_pipeline/downloads
            - clinvap_conf:/nextflow_pipeline/clinvap_conf
        depends_on:
            - flask
            - nginx
    sbml4j_db_setup:
        image: alpine
        volumes:
            - sbml4j_neo4j_vol:/vol
            - ./neo4j_backups:/neo4j_backups
        command: ["/bin/sh", "-c", "cd /vol && tar xfz /neo4j_backups/pecax.tar.gz --strip 1 && cd .. && chown -R 7474:7474 vol && chmod 600 /vol/conf/neo4j.conf"]
     
    sbml4j_db_backup:
        image: alpine
        volumes:
            - ./neo4j:/neo4j
            - ./neo4j_backups:/neo4j_backups
        command: ["/bin/sh", "-c", "cd /neo4j_backups && tar cfz pecax.tar.gz /neo4j"]
      
    apoc_install:
        image: alpine
        volumes:
            - ./neo4j/plugins:/plugins
        command: ["/bin/sh", "-c", "cd /plugins && wget https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.1.0.2/apoc-4.1.0.2-all.jar"]
    
    sbml4jdatabase:
        image: neo4j:4.1
        container_name: sbml4jdb
        volumes:
            - sbml4j_neo4j_vol:/vol
        expose:
            - "7474"
            - "7687"
        environment:
            - NEO4J_CONF=/vol/conf
            - NEO4J_dbms_security_auth__enabled=false
            - NEO4J_dbms_memory_pagecache_size=1G
            - NEO4J_dbms_memory_heap_initial__size=2G
            - NEO4J_dbms_memory_heap_max__size=2G
            - NEO4J_dbms_security_procedures_unrestricted=apoc.algo.dijkstraWithDefaultWeight, apoc.path.expand
            - NEO4J_dbms_security_procedures_whitelist=apoc.algo.dijkstraWithDefaultWeight, apoc.path.expand
        restart: unless-stopped
        command: ["neo4j"]
 
    sbml4j:
        image: thortiede/sbml4j:latest
        container_name: sbml4j
        volumes:
            - sbml4j_logs:/logs
        environment:
            - SPRING_PROFILES_ACTIVE=test
            - SPRING_DATA_NEO4j_URI=bolt://sbml4jdb:7687
            - SERVER_SERVLET_CONTEXTPATH=/sbml4j
            - SERVER_PORT=8080
            - OVERVIEWNETWORK_DEFAULT_BASE_NETWORK_U_U_I_D=f1234543-01e1-4939-b602-1b192fe4ba01
            - OVERVIEWNETWORK_DEFAULT_MINSIZE=1
            - OVERVIEWNETWORK_DEFAULT_MAXSIZE=2
            - OVERVIEWNETWORK_DEFAULT_TERMINATEATDRUG=True
            - OVERVIEWNETWORK_DEFAULT_DIRECTION=both
            - sbml4j.context.minSize=1
            - sbml4j.context.maxSize=3
            - sbml4j.context.terminateAt=Drug
            - sbml4j.context.direction=both
            - SBML4J_OUTPUT_HIDE_MODEL_U-U-I-DS=False
            - SBML4J_NETWORK_HARD-DELETE=True
            - SBML4j_FORCE-DELETE-OF-PUBLIC-NETWORK=False
            - SBML4J_NETWORK_USE-SHARED-PATHWAY-SEARCH=False
            - sbml4j.network.public-user=sbml4j
            - sbml4j.network.show-inactive-networks=false
            - sbml4j.network.allow-inactive-duplicates=true
            - SBML4J_ANNOTATION_APPEND=True
            - SBML4J_ANNOTATION_KEGGGENESSEPARATOR=+
            - SBML4J_annotation_annotate-with-links=True
            - sbml4j.csv.matching-column-name[0]=gene name
            - sbml4j.csv.matching-column-name[1]=genename
            - sbml4j.csv.matching-column-name[2]=gene symbol
            - sbml4j.csv.matching-column-name[3]=genesymbol
            - sbml4j.csv.matching-column-name[4]=gene
            - sbml4j.csv.matching-column-name[5]=symbol 
            - SBML4J_externalresources_mdanderson_add-md-anderson-annotation=True
            - SBML4J_externalresources_mdanderson_genelist=ABL1, AKT1, ALK, BRAF, CDK4, CDK6, CDKN2A, EGFR, ERBB2, FGFR1, FGFR2, FLT3, IDH1, KDR, KIT, KRAS, MDM2, MET, NRAS, NTRK1, NTRK2, PDGFRA, PIK3CA, PIK3R1, PTCH1, PTEN, PTPN11, PET, ROS1, SMO
            - SBML4J_externalresources_mdanderson_baseurl=https://pct.mdanderson.org/home/
            - SBML4J_externalresources_mdanderson_section=Overview
            - SBML4J_externalresources_biologicalqualifer_default-database=KEGG
            - SBML4J_externalresources_keggdatabase_pathway-link-prefix=https://www.genome.jp/kegg-bin/show_pathway?
            - SBML4J_externalresources_keggdatabase_pathway-search-prefix=https://www.genome.jp/dbget-bin/www_bfind_sub?dbkey=pathway&keywords=
        depends_on:
            - "sbml4jdatabase"
        expose:
            - "8080"
        restart: on-failure
volumes:
    clinvap_uploads:
    clinvap_downloads:
    clinvap_conf:
    sbml4j_logs:
    sbml4j_neo4j_vol:
    arangodb_data_container:
    arangodb_apps_data_container:
